site_name: Louisiana Mesh Community Docs
site_url: https://docs.louisianamesh.org/
theme:
  name: material
  palette:

      # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light green
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light green
      accent: deep purple

nav:
  - Home: index.md
  - Local Settings and Information:
    - Meshcore Frequency's For Louisiana: freq-settings.md
    - Meshcore Channel's In Louisiana: channels.md
  - Hardware & Guides:
    - What Device should I buy?: devicerecs.md
    - What Antenna should I use?: antenna.md
    - Our Standard repeater build: diy-repeater-builds.md
  - Setup Guides:
    - Setting up a Meshcore Companion: setting-up-meshcore-companion.md
    - How to setup a Meshcore Repeater: meshcore-repeater-setup.md
  - Community Transparency: transparency.md


extra:
  

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LouisianaMeshCommunity

    - icon: fontawesome/brands/discord
      link: https://discord.louisianamesh.org

    - icon: fontawesome/solid/hand-holding-usd
      link: https://ko-fi.com/louisianameshcommunity
